general = {
    name = "MusicBox AirPlay";
    interpolation = "basic";
    output_backend = "pa";
};

sessioncontrol = {
    allow_session_interruption = "yes";
};

pa = {
    application_name = "MusicBox AirPlay";
};

alsa = {
    output_device = "default";
};
